<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1E7MQ28" failures="1" tests="2" name="runner.Scenario_outlinr_runner" time="13.775" errors="0" timestamp="2024-09-25T19:34:17 IST" skipped="0">
  <testcase classname="runner.Scenario_outlinr_runner" name="runScenario" time="5.114">
    <failure message="expected [https://www.demoblaze.com/prod.html?idp_=2] but found [https://www.demoblaze.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.demoblaze.com/prod.html?idp_=2] but found [https://www.demoblaze.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdef.Scenario_outline_practice.productPageShouldCome(Scenario_outline_practice.java:53)
at âœ½.product page "https://www.demoblaze.com/prod.html?idp_=2" should come(file:///C:/automation/cucumber_ler/src/test/java/featureORuserstory/scenariooutline_login.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.Scenario_outlinr_runner" name="runScenario" time="8.661"/>
  <system-out/>
</testsuite> <!-- runner.Scenario_outlinr_runner -->
